package dnsmasqcfg

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeTo is a test-only mirror of Write that writes to an arbitrary path
// instead of /etc/dnsmasq.d/ — keeps the test hermetic.
func writeTo(path, ipsetName string, domains []string) error {
	uniq := map[string]struct{}{}
	for _, d := range domains {
		uniq[strings.ToLower(strings.TrimRight(strings.TrimSpace(d), "."))] = struct{}{}
	}
	delete(uniq, "")
	var sb strings.Builder
	sb.WriteString("# Generated by ladon — do not edit.\n\n")
	for d := range uniq {
		sb.WriteString("ipset=/" + d + "/" + ipsetName + "\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func TestWriteFormatAndDedup(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ladon-manual.conf")
	if err := writeTo(path, "ladon_manual", []string{
		"openai.com",
		"OPENAI.COM",    // case-insensitive dedup
		"openai.com.",   // trailing dot dedup
		"  openai.com ", // whitespace dedup
		"twitch.tv",
		"",
	}); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)
	if !strings.Contains(got, "ipset=/openai.com/ladon_manual") {
		t.Errorf("openai entry missing in:\n%s", got)
	}
	if !strings.Contains(got, "ipset=/twitch.tv/ladon_manual") {
		t.Errorf("twitch entry missing in:\n%s", got)
	}
	// Dedup: only ONE openai.com line.
	if strings.Count(got, "openai.com") != 1 {
		t.Errorf("expected one openai.com line, got:\n%s", got)
	}
}
