// Package dnsmasqcfg writes a dnsmasq.d snippet that delegates manual-allow
// and extension domains to dnsmasq's native ipset= directive. dnsmasq then
// populates the kernel ipset synchronously during DNS resolution — including
// walking CNAME chains and adding all final A-records — which closes the
// timing race ladon's tail-and-reconcile loop can't ever win for the very
// first TCP SYN after a fresh resolve.
package dnsmasqcfg

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// DefaultPath is the Debian/Ubuntu drop-in location. OpenWRT passes
// /tmp/dnsmasq.d/ladon-manual.conf instead — the path is operator-configurable
// via engine.Config.DnsmasqConfPath (YAML: dnsmasq.conf_path).
const DefaultPath = "/etc/dnsmasq.d/ladon-manual.conf"

// DefaultRestartCmd is the systemd incantation. OpenWRT operators pass
// "/etc/init.d/dnsmasq reload" instead via engine.Config.DnsmasqRestartCmd.
const DefaultRestartCmd = "systemctl restart dnsmasq"

// Write produces the snippet at path. Atomic via tmp+rename so dnsmasq
// never observes a half-written file. Empty domains list still writes a
// stub — keeps file present for operator visibility, dnsmasq treats it
// as a no-op include.
func Write(path, ipsetName string, domains []string) error {
	if path == "" {
		return fmt.Errorf("dnsmasqcfg: empty path")
	}
	if ipsetName == "" {
		return fmt.Errorf("dnsmasqcfg: empty ipset name")
	}
	uniq := make(map[string]struct{}, len(domains))
	for _, d := range domains {
		d = strings.ToLower(strings.TrimSpace(strings.TrimRight(d, ".")))
		if d == "" {
			continue
		}
		uniq[d] = struct{}{}
	}
	sorted := make([]string, 0, len(uniq))
	for d := range uniq {
		sorted = append(sorted, d)
	}
	sort.Strings(sorted)

	var sb strings.Builder
	sb.WriteString("# Generated by ladon — do not edit.\n")
	sb.WriteString("# Source: manual-allow.txt + enabled extensions.\n")
	sb.WriteString("# dnsmasq populates the ipset synchronously during DNS resolution,\n")
	sb.WriteString("# walking CNAME chains, so the first TCP SYN after a fresh resolve\n")
	sb.WriteString("# already finds its destination IP in the kernel set.\n\n")
	for _, d := range sorted {
		fmt.Fprintf(&sb, "ipset=/%s/%s\n", d, ipsetName)
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".ladon-manual.conf.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.WriteString(sb.String()); err != nil {
		tmp.Close()
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename %s: %w", path, err)
	}
	return nil
}

// Restart runs the operator-configured restart command (whitespace-split) so
// dnsmasq re-reads its drop-ins — SIGHUP only re-reads /etc/resolv.conf and
// /etc/hosts, the `ipset=` directives we write are parsed at startup and
// ignored on reload.
//
// On Debian/Ubuntu the default is `systemctl restart dnsmasq`; on OpenWRT
// the install script puts `/etc/init.d/dnsmasq reload` in config.yaml.
// Empty cmd is a no-op — useful in tests and for setups where the operator
// wants to bounce dnsmasq themselves.
func Restart(ctx context.Context, cmd string) error {
	cmd = strings.TrimSpace(cmd)
	if cmd == "" {
		return nil
	}
	parts := strings.Fields(cmd)
	c := exec.CommandContext(ctx, parts[0], parts[1:]...)
	out, err := c.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %w (output: %s)", cmd, err, strings.TrimSpace(string(out)))
	}
	return nil
}
